ignoredBuiltDependencies:
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild

patchedDependencies:
  '@thallesp/nestjs-better-auth': patches/@thallesp__nestjs-better-auth+2.2.0.patch
  better-call: patches/better-call+1.1.7.patch
