/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type AdminSessionEntityControllerFindAllOrder =
  (typeof AdminSessionEntityControllerFindAllOrder)[keyof typeof AdminSessionEntityControllerFindAllOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminSessionEntityControllerFindAllOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
