/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { AdminUserEntityControllerFindAllOrder } from './adminUserEntityControllerFindAllOrder';

export type AdminUserEntityControllerFindAllParams = {
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  sort?: string;
  order?: AdminUserEntityControllerFindAllOrder;
  filter?: string;
};
