/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type AdminUsersControllerFindAllOrder =
  (typeof AdminUsersControllerFindAllOrder)[keyof typeof AdminUsersControllerFindAllOrder];

export const AdminUsersControllerFindAllOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
