/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { AdminSessionEntityControllerFindAllOrder } from './adminSessionEntityControllerFindAllOrder';

export type AdminSessionEntityControllerFindAllParams = {
  /**
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  sort?: string;
  order?: AdminSessionEntityControllerFindAllOrder;
  filter?: string;
};
