/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type AdminUserEntityControllerFindAllOrder =
  (typeof AdminUserEntityControllerFindAllOrder)[keyof typeof AdminUserEntityControllerFindAllOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUserEntityControllerFindAllOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
