/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type AdminSessionEntityControllerFindAllOrder =
  (typeof AdminSessionEntityControllerFindAllOrder)[keyof typeof AdminSessionEntityControllerFindAllOrder];

export const AdminSessionEntityControllerFindAllOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
