/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ChangePasswordBody = {
  /** The new password to set */
  newPassword: string;
  /** The current password is required */
  currentPassword: string;
  /** Must be a boolean value */
  revokeOtherSessions?: boolean | null;
};
