/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ChangePassword200User } from './changePassword200User';

export type ChangePassword200 = {
  /**
   * New session token if other sessions were revoked
   * @nullable
   */
  token?: string | null;
  user: ChangePassword200User;
};
