/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Status message of the email change process
 * @nullable
 */
export type ChangeEmail200Message =
  | (typeof ChangeEmail200Message)[keyof typeof ChangeEmail200Message]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeEmail200Message = {
  Email_updated: 'Email updated',
  Verification_email_sent: 'Verification email sent',
} as const;
