/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ChangePasswordBody = {
  /** The new password to set */
  newPassword: string;
  /** The current password is required */
  currentPassword: string;
  /**
   * Must be a boolean value
   * @nullable
   */
  revokeOtherSessions?: boolean | null;
};
