/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ChangeEmailBody = {
  /** The new email address to set must be a valid email address */
  newEmail: string;
  /**
   * The URL to redirect to after email verification
   * @nullable
   */
  callbackURL?: string | null;
};
