/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

import type { ChangeEmail200Message } from './changeEmail200Message';
import type { User } from './user';

export type ChangeEmail200 = {
  user?: User;
  /** Indicates if the request was successful */
  status: boolean;
  /**
   * Status message of the email change process
   * @nullable
   */
  message?: ChangeEmail200Message;
};
