/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type CreateProductDtoCurrency =
  (typeof CreateProductDtoCurrency)[keyof typeof CreateProductDtoCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProductDtoCurrency = {
  USD: 'USD',
  EUR: 'EUR',
  RUB: 'RUB',
} as const;
