/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type CreateProductDtoStatus =
  (typeof CreateProductDtoStatus)[keyof typeof CreateProductDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProductDtoStatus = {
  draft: 'draft',
  active: 'active',
  archived: 'archived',
  out_of_stock: 'out_of_stock',
} as const;
