/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Status message of the deletion process
 */
export type DeleteUser200Message = (typeof DeleteUser200Message)[keyof typeof DeleteUser200Message];

export const DeleteUser200Message = {
  User_deleted: 'User deleted',
  Verification_email_sent: 'Verification email sent',
} as const;
