/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export interface ErrorDetailsDto {
  /** Database constraint name (e.g., "users_email_key") */
  constraint?: string;
  /** Database table name */
  table?: string;
  /** Database column name */
  column?: string;
  /** PostgreSQL error detail message */
  detail?: string;
}
