/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Application error code for i18n and client-side handling
 */
export type ErrorResponseDtoCode = (typeof ErrorResponseDtoCode)[keyof typeof ErrorResponseDtoCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorResponseDtoCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_VALIDATION_ERROR: 'DATABASE_VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  DATABASE_CONFLICT_ERROR: 'DATABASE_CONFLICT_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;
