/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ForgetPasswordWithEmailOTP200 = {
  /** Indicates if the OTP was sent successfully */
  success?: boolean;
};
