/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Confirmation message
 */
export type GetAuthDeleteUserCallback200Message =
  (typeof GetAuthDeleteUserCallback200Message)[keyof typeof GetAuthDeleteUserCallback200Message];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuthDeleteUserCallback200Message = {
  User_deleted: 'User deleted',
} as const;
