/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { GetAuthDeleteUserCallback200Message } from './getAuthDeleteUserCallback200Message';

export type GetAuthDeleteUserCallback200 = {
  /** Indicates if the deletion was successful */
  success: boolean;
  /** Confirmation message */
  message: GetAuthDeleteUserCallback200Message;
};
