/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { Session } from './session';
import type { User } from './user';

export type GetSession200 = {
  session: Session;
  user: User;
} | null;
