/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { Session } from './session';
import type { User } from './user';

/**
 * @nullable
 */
export type GetSession200 = {
  session: Session;
  user: User;
} | null;
