/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

import type { HealthControllerCheck503Details } from './healthControllerCheck503Details';
import type { HealthControllerCheck503Error } from './healthControllerCheck503Error';
import type { HealthControllerCheck503Info } from './healthControllerCheck503Info';

export type HealthControllerCheck503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};
