/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type LinkSocialAccountBodyIdToken = {
  token: string;
  nonce?: string | null;
  accessToken?: string | null;
  refreshToken?: string | null;
  scopes?: string[] | null;
} | null;
