/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LinkSocialAccountBodyIdToken } from './linkSocialAccountBodyIdToken';

export type LinkSocialAccountBody = {
  /**
   * The URL to redirect to after the user has signed in
   * @nullable
   */
  callbackURL?: string | null;
  provider: string;
  /** @nullable */
  idToken?: LinkSocialAccountBodyIdToken;
  /** @nullable */
  requestSignUp?: boolean | null;
  /**
   * Additional scopes to request from the provider
   * @nullable
   */
  scopes?: string[] | null;
  /**
   * The URL to redirect to if there is an error during the link process
   * @nullable
   */
  errorCallbackURL?: string | null;
  /**
   * Disable automatic redirection to the provider. Useful for handling the redirection yourself
   * @nullable
   */
  disableRedirect?: boolean | null;
  /** @nullable */
  additionalData?: string | null;
};
