/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type LinkSocialAccountBodyIdToken = {
  token: string;
  /** @nullable */
  nonce?: string | null;
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  scopes?: string[] | null;
} | null;
