/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ProductResponseDto } from './productResponseDto';

export interface PatchProductResponseDto {
  message: string;
  product: ProductResponseDto;
}
