/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type PostAuthRevokeSession200 = {
  /** Indicates if the session was revoked successfully */
  status: boolean;
};
