/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export type PostAuthEmailOtpVerifyEmail200 = {
  /** Indicates if the verification was successful */
  status: boolean;
  /**
   * Session token if autoSignInAfterVerification is enabled, otherwise null
   * @nullable
   */
  token: string | null;
  user: User;
};
