/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type PostAuthRevokeOtherSessions200 = {
  /** Indicates if all other sessions were revoked successfully */
  status: boolean;
};
