/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type PostAuthGetAccessTokenBody = {
  /** The provider ID for the OAuth provider */
  providerId: string;
  /**
   * The account ID associated with the refresh token
   * @nullable
   */
  accountId?: string | null;
  /**
   * The user ID associated with the account
   * @nullable
   */
  userId?: string | null;
};
