/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerFindAllSortOrder =
  (typeof ProductsControllerFindAllSortOrder)[keyof typeof ProductsControllerFindAllSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
