/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerGetMineSortBy =
  (typeof ProductsControllerGetMineSortBy)[keyof typeof ProductsControllerGetMineSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductsControllerGetMineSortBy = {
  name: 'name',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;
