/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ProductsControllerFindAllCategory } from './productsControllerFindAllCategory';
import type { ProductsControllerFindAllSortBy } from './productsControllerFindAllSortBy';
import type { ProductsControllerFindAllSortOrder } from './productsControllerFindAllSortOrder';
import type { ProductsControllerFindAllStatus } from './productsControllerFindAllStatus';

export type ProductsControllerFindAllParams = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  category?: ProductsControllerFindAllCategory;
  status?: ProductsControllerFindAllStatus;
  /**
   */
  minPrice?: number;
  /**
   */
  maxPrice?: number;
  inStock?: boolean;
  /**
   * @minLength 1
   * @maxLength 100
   */
  search?: string;
  sortBy?: ProductsControllerFindAllSortBy;
  sortOrder?: ProductsControllerFindAllSortOrder;
};
