/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerGetMineStatus =
  (typeof ProductsControllerGetMineStatus)[keyof typeof ProductsControllerGetMineStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductsControllerGetMineStatus = {
  draft: 'draft',
  active: 'active',
  archived: 'archived',
  out_of_stock: 'out_of_stock',
} as const;
