/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ProductsControllerGetMineCategory } from './productsControllerGetMineCategory';
import type { ProductsControllerGetMineSortBy } from './productsControllerGetMineSortBy';
import type { ProductsControllerGetMineSortOrder } from './productsControllerGetMineSortOrder';
import type { ProductsControllerGetMineStatus } from './productsControllerGetMineStatus';

export type ProductsControllerGetMineParams = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  category?: ProductsControllerGetMineCategory;
  status?: ProductsControllerGetMineStatus;
  /**
   */
  minPrice?: number;
  /**
   */
  maxPrice?: number;
  inStock?: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  search?: string;
  sortBy?: ProductsControllerGetMineSortBy;
  sortOrder?: ProductsControllerGetMineSortOrder;
};
