/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerFindAllCategory =
  (typeof ProductsControllerFindAllCategory)[keyof typeof ProductsControllerFindAllCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductsControllerFindAllCategory = {
  electronics: 'electronics',
  clothing: 'clothing',
  food: 'food',
  books: 'books',
  toys: 'toys',
  other: 'other',
} as const;
