/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerFindAllSortBy =
  (typeof ProductsControllerFindAllSortBy)[keyof typeof ProductsControllerFindAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductsControllerFindAllSortBy = {
  name: 'name',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;
