/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerGetMineCategory =
  (typeof ProductsControllerGetMineCategory)[keyof typeof ProductsControllerGetMineCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductsControllerGetMineCategory = {
  electronics: 'electronics',
  clothing: 'clothing',
  food: 'food',
  books: 'books',
  toys: 'toys',
  other: 'other',
} as const;
