/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ResetPasswordBody = {
  /** The new password to set */
  newPassword: string;
  /**
   * The token to reset the password
   * @nullable
   */
  token?: string | null;
};
