/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type SendVerificationEmailBody = {
  /** The email to send the verification email to */
  email: string;
  /**
   * The URL to use for email verification callback
   * @nullable
   */
  callbackURL?: string | null;
};
