/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type SendVerificationEmail200 = {
  /** Indicates if the email was sent successfully */
  status?: boolean;
};
