/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type SendEmailVerificationOTPBody = {
  /** Email address to send the OTP */
  email: string;
  /** Type of the OTP */
  type: string;
};
