/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export type SignInWithEmailOTP200 = {
  /** Session token for the authenticated session */
  token: string;
  user: User;
};
