/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

/**
 * Session response when idToken is provided
 */
export type SignInEmail200 = {
  redirect: boolean;
  /** Session token */
  token: string;
  /** @nullable */
  url?: string | null;
  user: User;
};
