/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type SignInEmailBody = {
  /** Email of the user */
  email: string;
  /** Password of the user */
  password: string;
  /** Callback URL to use as a redirect for email verification */
  callbackURL?: string | null;
  rememberMe?: string | null;
};
