/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type SocialSignInBodyIdToken = {
  /** ID token from the provider */
  token: string;
  /**
   * Nonce used to generate the token
   * @nullable
   */
  nonce?: string | null;
  /**
   * Access token from the provider
   * @nullable
   */
  accessToken?: string | null;
  /**
   * Refresh token from the provider
   * @nullable
   */
  refreshToken?: string | null;
  /**
   * Expiry date of the token
   * @nullable
   */
  expiresAt?: number | null;
} | null;
