/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateProductDtoMetadataDimensions } from './updateProductDtoMetadataDimensions';

export type UpdateProductDtoMetadata = {
  /** @minLength 1 */
  brand?: string;
  /** @minLength 1 */
  manufacturer?: string;
  /** @minLength 1 */
  sku?: string;
  /** @minLength 1 */
  barcode?: string;
  /** */
  weight?: number;
  dimensions?: UpdateProductDtoMetadataDimensions;
};
