/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type UpdateUserBody = {
  /** The name of the user */
  name?: string;
  /**
   * The image of the user
   * @nullable
   */
  image?: string | null;
};
