/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type UpdateUserBody = {
  /** The name of the user */
  name?: string;
  /** The image of the user */
  image?: string | null;
};
