/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export interface ValidationErrorItemDto {
  /** Error code (e.g., invalid_type, invalid_format, too_small) */
  code: string;
  /** Path to the field that failed validation */
  path: string[];
  /** Human-readable error message */
  message: string;
  /** Expected type or format */
  expected?: string;
  /** Minimum value (for too_small errors) */
  minimum?: number;
  /** Format expected (for invalid_format errors) */
  format?: string;
}
