/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export interface ValidationErrorDto {
  /** Field path (e.g., "email", "user.address.city") */
  field: string;
  /** Validation error message */
  message: string;
  /** Validation rule that failed (e.g., "required", "email", "min") */
  rule?: string;
}
