/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateProductDtoMetadataDimensions } from './createProductDtoMetadataDimensions';

export type CreateProductDtoMetadata = {
  /** @minLength 1 */
  brand?: string;
  /** @minLength 1 */
  manufacturer?: string;
  /** @minLength 1 */
  sku?: string;
  /** @minLength 1 */
  barcode?: string;
  /** */
  weight?: number;
  dimensions?: CreateProductDtoMetadataDimensions;
};
