/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

import type { HealthControllerCheck200Details } from './healthControllerCheck200Details';
import type { HealthControllerCheck200Error } from './healthControllerCheck200Error';
import type { HealthControllerCheck200Info } from './healthControllerCheck200Info';

export type HealthControllerCheck200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck200Info;
  /** @nullable */
  error?: HealthControllerCheck200Error;
  details?: HealthControllerCheck200Details;
};
