/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerGetMineSortOrder =
  (typeof ProductsControllerGetMineSortOrder)[keyof typeof ProductsControllerGetMineSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductsControllerGetMineSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
