/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type UpdateProductDtoStatus =
  (typeof UpdateProductDtoStatus)[keyof typeof UpdateProductDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProductDtoStatus = {
  draft: 'draft',
  active: 'active',
  archived: 'archived',
  out_of_stock: 'out_of_stock',
} as const;
