/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ValidationErrorItemDto } from './validationErrorItemDto';

export interface ValidationErrorDto {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Array of validation errors */
  errors: ValidationErrorItemDto[];
}
