/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type {
  ChangeEmail200,
  ChangeEmailBody,
  ChangePassword200,
  ChangePasswordBody,
  CreateProductDto,
  CreateProductResponseDto,
  DeleteUser200,
  DeleteUserBody,
  GetAuthAccountInfo200,
  GetAuthDeleteUserCallback200,
  GetAuthDeleteUserCallbackParams,
  GetAuthOk200,
  GetAuthVerifyEmail200,
  GetAuthVerifyEmailParams,
  GetProductResponseDto,
  GetSession200,
  HealthControllerCheck200,
  LinkSocialAccount200,
  LinkSocialAccountBody,
  ListUserAccounts200Item,
  PaginatedProductsResponseDto,
  PatchProductResponseDto,
  PostAuthGetAccessToken200,
  PostAuthGetAccessTokenBody,
  PostAuthRefreshToken200,
  PostAuthRefreshTokenBody,
  PostAuthRevokeOtherSessions200,
  PostAuthRevokeOtherSessionsBody,
  PostAuthRevokeSession200,
  PostAuthRevokeSessionBody,
  PostAuthRevokeSessions200,
  PostAuthRevokeSessionsBody,
  PostAuthUnlinkAccount200,
  PostAuthUnlinkAccountBody,
  ProductsControllerFindAllParams,
  ProductsControllerGetMineParams,
  RequestPasswordReset200,
  RequestPasswordResetBody,
  ResetPassword200,
  ResetPasswordBody,
  ResetPasswordCallback200,
  ResetPasswordCallbackParams,
  SendVerificationEmail200,
  SendVerificationEmailBody,
  Session,
  SignInEmail200,
  SignInEmailBody,
  SignOut200,
  SignOutBody,
  SignUpWithEmailAndPassword200,
  SignUpWithEmailAndPasswordBody,
  SocialSignIn200,
  SocialSignInBody,
  UpdateProductDto,
  UpdateProductResponseDto,
  UpdateUser200,
  UpdateUserBody,
} from './model';

import { request } from './mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get hello message (public route)
 */
export const appControllerGetHello = (options?: SecondParameter<typeof request<void>>) => {
  return request<void>({ url: `/`, method: 'GET' }, options);
};

export const metricsControllerIndex = (options?: SecondParameter<typeof request<void>>) => {
  return request<void>({ url: `/metrics`, method: 'GET' }, options);
};

/**
 * @summary Health check endpoint
 */
export const healthControllerCheck = (
  options?: SecondParameter<typeof request<HealthControllerCheck200>>
) => {
  return request<HealthControllerCheck200>({ url: `/health`, method: 'GET' }, options);
};

/**
 * @summary Create a new product (requires authentication)
 */
export const productsControllerCreate = (
  createProductDto: CreateProductDto,
  options?: SecondParameter<typeof request<CreateProductResponseDto>>
) => {
  return request<CreateProductResponseDto>(
    {
      url: `/products`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createProductDto,
    },
    options
  );
};

/**
 * Supports query parameters for filtering by category, status, price range, stock availability, search, sorting, and pagination
 * @summary Get all products with filtering, sorting, and pagination
 */
export const productsControllerFindAll = (
  params?: ProductsControllerFindAllParams,
  options?: SecondParameter<typeof request<PaginatedProductsResponseDto>>
) => {
  return request<PaginatedProductsResponseDto>(
    { url: `/products`, method: 'GET', params },
    options
  );
};

/**
 * Example of a protected route that requires authentication. Returns all products created by the current user with filtering, sorting, and pagination.
 * @summary Get current user products (protected route)
 */
export const productsControllerGetMine = (
  params?: ProductsControllerGetMineParams,
  options?: SecondParameter<typeof request<PaginatedProductsResponseDto>>
) => {
  return request<PaginatedProductsResponseDto>(
    { url: `/products/mine`, method: 'GET', params },
    options
  );
};

/**
 * Returns product details. If authenticated and the product belongs to the current user, includes isOwner flag.
 * @summary Get a product by ID
 */
export const productsControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof request<GetProductResponseDto>>
) => {
  return request<GetProductResponseDto>({ url: `/products/${id}`, method: 'GET' }, options);
};

/**
 * Replaces the entire product with the provided data. Required fields: name, price, category. Other fields are optional or have default values.
 * @summary Update a product (full update, requires authentication)
 */
export const productsControllerUpdate = (
  id: string,
  createProductDto: CreateProductDto,
  options?: SecondParameter<typeof request<UpdateProductResponseDto>>
) => {
  return request<UpdateProductResponseDto>(
    {
      url: `/products/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: createProductDto,
    },
    options
  );
};

/**
 * Updates only the provided fields. All fields are optional. Tests PATCH body parser.
 * @summary Partially update a product (requires authentication)
 */
export const productsControllerPatch = (
  id: string,
  updateProductDto: UpdateProductDto,
  options?: SecondParameter<typeof request<PatchProductResponseDto>>
) => {
  return request<PatchProductResponseDto>(
    {
      url: `/products/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateProductDto,
    },
    options
  );
};

/**
 * @summary Delete a product (requires authentication)
 */
export const productsControllerRemove = (
  id: string,
  options?: SecondParameter<typeof request<void>>
) => {
  return request<void>({ url: `/products/${id}`, method: 'DELETE' }, options);
};

/**
 * Sign in with a social provider
 */
export const socialSignIn = (
  socialSignInBody: SocialSignInBody,
  options?: SecondParameter<typeof request<SocialSignIn200>>
) => {
  return request<SocialSignIn200>(
    {
      url: `/auth/sign-in/social`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: socialSignInBody,
    },
    options
  );
};

/**
 * Get the current session
 */
export const getSession = (options?: SecondParameter<typeof request<GetSession200>>) => {
  return request<GetSession200>({ url: `/auth/get-session`, method: 'GET' }, options);
};

/**
 * Sign out the current user
 */
export const signOut = (
  signOutBody: SignOutBody,
  options?: SecondParameter<typeof request<SignOut200>>
) => {
  return request<SignOut200>(
    {
      url: `/auth/sign-out`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signOutBody,
    },
    options
  );
};

/**
 * Sign up a user using email and password
 */
export const signUpWithEmailAndPassword = (
  signUpWithEmailAndPasswordBody: SignUpWithEmailAndPasswordBody,
  options?: SecondParameter<typeof request<SignUpWithEmailAndPassword200>>
) => {
  return request<SignUpWithEmailAndPassword200>(
    {
      url: `/auth/sign-up/email`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signUpWithEmailAndPasswordBody,
    },
    options
  );
};

/**
 * Sign in with email and password
 */
export const signInEmail = (
  signInEmailBody: SignInEmailBody,
  options?: SecondParameter<typeof request<SignInEmail200>>
) => {
  return request<SignInEmail200>(
    {
      url: `/auth/sign-in/email`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signInEmailBody,
    },
    options
  );
};

/**
 * Reset the password for a user
 */
export const resetPassword = (
  resetPasswordBody: ResetPasswordBody,
  options?: SecondParameter<typeof request<ResetPassword200>>
) => {
  return request<ResetPassword200>(
    {
      url: `/auth/reset-password`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resetPasswordBody,
    },
    options
  );
};

/**
 * Verify the email of the user
 */
export const getAuthVerifyEmail = (
  params: GetAuthVerifyEmailParams,
  options?: SecondParameter<typeof request<GetAuthVerifyEmail200>>
) => {
  return request<GetAuthVerifyEmail200>(
    { url: `/auth/verify-email`, method: 'GET', params },
    options
  );
};

/**
 * Send a verification email to the user
 */
export const sendVerificationEmail = (
  sendVerificationEmailBody: SendVerificationEmailBody,
  options?: SecondParameter<typeof request<SendVerificationEmail200>>
) => {
  return request<SendVerificationEmail200>(
    {
      url: `/auth/send-verification-email`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sendVerificationEmailBody,
    },
    options
  );
};

export const changeEmail = (
  changeEmailBody: ChangeEmailBody,
  options?: SecondParameter<typeof request<ChangeEmail200>>
) => {
  return request<ChangeEmail200>(
    {
      url: `/auth/change-email`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: changeEmailBody,
    },
    options
  );
};

/**
 * Change the password of the user
 */
export const changePassword = (
  changePasswordBody: ChangePasswordBody,
  options?: SecondParameter<typeof request<ChangePassword200>>
) => {
  return request<ChangePassword200>(
    {
      url: `/auth/change-password`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: changePasswordBody,
    },
    options
  );
};

/**
 * Update the current user
 */
export const updateUser = (
  updateUserBody: UpdateUserBody,
  options?: SecondParameter<typeof request<UpdateUser200>>
) => {
  return request<UpdateUser200>(
    {
      url: `/auth/update-user`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateUserBody,
    },
    options
  );
};

/**
 * Delete the user
 */
export const deleteUser = (
  deleteUserBody: DeleteUserBody,
  options?: SecondParameter<typeof request<DeleteUser200>>
) => {
  return request<DeleteUser200>(
    {
      url: `/auth/delete-user`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deleteUserBody,
    },
    options
  );
};

/**
 * Send a password reset email to the user
 */
export const requestPasswordReset = (
  requestPasswordResetBody: RequestPasswordResetBody,
  options?: SecondParameter<typeof request<RequestPasswordReset200>>
) => {
  return request<RequestPasswordReset200>(
    {
      url: `/auth/request-password-reset`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: requestPasswordResetBody,
    },
    options
  );
};

/**
 * Redirects the user to the callback URL with the token
 */
export const resetPasswordCallback = (
  token: string,
  params: ResetPasswordCallbackParams,
  options?: SecondParameter<typeof request<ResetPasswordCallback200>>
) => {
  return request<ResetPasswordCallback200>(
    { url: `/auth/reset-password/${token}`, method: 'GET', params },
    options
  );
};

/**
 * List all active sessions for the user
 */
export const listUserSessions = (options?: SecondParameter<typeof request<Session[]>>) => {
  return request<Session[]>({ url: `/auth/list-sessions`, method: 'GET' }, options);
};

/**
 * Revoke a single session
 */
export const postAuthRevokeSession = (
  postAuthRevokeSessionBody: PostAuthRevokeSessionBody,
  options?: SecondParameter<typeof request<PostAuthRevokeSession200>>
) => {
  return request<PostAuthRevokeSession200>(
    {
      url: `/auth/revoke-session`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthRevokeSessionBody,
    },
    options
  );
};

/**
 * Revoke all sessions for the user
 */
export const postAuthRevokeSessions = (
  postAuthRevokeSessionsBody: PostAuthRevokeSessionsBody,
  options?: SecondParameter<typeof request<PostAuthRevokeSessions200>>
) => {
  return request<PostAuthRevokeSessions200>(
    {
      url: `/auth/revoke-sessions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthRevokeSessionsBody,
    },
    options
  );
};

/**
 * Revoke all other sessions for the user except the current one
 */
export const postAuthRevokeOtherSessions = (
  postAuthRevokeOtherSessionsBody: PostAuthRevokeOtherSessionsBody,
  options?: SecondParameter<typeof request<PostAuthRevokeOtherSessions200>>
) => {
  return request<PostAuthRevokeOtherSessions200>(
    {
      url: `/auth/revoke-other-sessions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthRevokeOtherSessionsBody,
    },
    options
  );
};

/**
 * Link a social account to the user
 */
export const linkSocialAccount = (
  linkSocialAccountBody: LinkSocialAccountBody,
  options?: SecondParameter<typeof request<LinkSocialAccount200>>
) => {
  return request<LinkSocialAccount200>(
    {
      url: `/auth/link-social`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: linkSocialAccountBody,
    },
    options
  );
};

/**
 * List all accounts linked to the user
 */
export const listUserAccounts = (
  options?: SecondParameter<typeof request<ListUserAccounts200Item[]>>
) => {
  return request<ListUserAccounts200Item[]>({ url: `/auth/list-accounts`, method: 'GET' }, options);
};

/**
 * Callback to complete user deletion with verification token
 */
export const getAuthDeleteUserCallback = (
  params?: GetAuthDeleteUserCallbackParams,
  options?: SecondParameter<typeof request<GetAuthDeleteUserCallback200>>
) => {
  return request<GetAuthDeleteUserCallback200>(
    { url: `/auth/delete-user/callback`, method: 'GET', params },
    options
  );
};

/**
 * Unlink an account
 */
export const postAuthUnlinkAccount = (
  postAuthUnlinkAccountBody: PostAuthUnlinkAccountBody,
  options?: SecondParameter<typeof request<PostAuthUnlinkAccount200>>
) => {
  return request<PostAuthUnlinkAccount200>(
    {
      url: `/auth/unlink-account`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthUnlinkAccountBody,
    },
    options
  );
};

/**
 * Refresh the access token using a refresh token
 */
export const postAuthRefreshToken = (
  postAuthRefreshTokenBody: PostAuthRefreshTokenBody,
  options?: SecondParameter<typeof request<PostAuthRefreshToken200>>
) => {
  return request<PostAuthRefreshToken200>(
    {
      url: `/auth/refresh-token`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthRefreshTokenBody,
    },
    options
  );
};

/**
 * Get a valid access token, doing a refresh if needed
 */
export const postAuthGetAccessToken = (
  postAuthGetAccessTokenBody: PostAuthGetAccessTokenBody,
  options?: SecondParameter<typeof request<PostAuthGetAccessToken200>>
) => {
  return request<PostAuthGetAccessToken200>(
    {
      url: `/auth/get-access-token`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthGetAccessTokenBody,
    },
    options
  );
};

/**
 * Get the account info provided by the provider
 */
export const getAuthAccountInfo = (
  options?: SecondParameter<typeof request<GetAuthAccountInfo200>>
) => {
  return request<GetAuthAccountInfo200>({ url: `/auth/account-info`, method: 'GET' }, options);
};

/**
 * Check if the API is working
 */
export const getAuthOk = (options?: SecondParameter<typeof request<GetAuthOk200>>) => {
  return request<GetAuthOk200>({ url: `/auth/ok`, method: 'GET' }, options);
};

/**
 * Displays an error page
 */
export const getAuthError = (options?: SecondParameter<typeof request<string>>) => {
  return request<string>({ url: `/auth/error`, method: 'GET' }, options);
};

export type AppControllerGetHelloResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetHello>>
>;
export type MetricsControllerIndexResult = NonNullable<
  Awaited<ReturnType<typeof metricsControllerIndex>>
>;
export type HealthControllerCheckResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerCheck>>
>;
export type ProductsControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerCreate>>
>;
export type ProductsControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerFindAll>>
>;
export type ProductsControllerGetMineResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerGetMine>>
>;
export type ProductsControllerFindOneResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerFindOne>>
>;
export type ProductsControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerUpdate>>
>;
export type ProductsControllerPatchResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerPatch>>
>;
export type ProductsControllerRemoveResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerRemove>>
>;
export type SocialSignInResult = NonNullable<Awaited<ReturnType<typeof socialSignIn>>>;
export type GetSessionResult = NonNullable<Awaited<ReturnType<typeof getSession>>>;
export type SignOutResult = NonNullable<Awaited<ReturnType<typeof signOut>>>;
export type SignUpWithEmailAndPasswordResult = NonNullable<
  Awaited<ReturnType<typeof signUpWithEmailAndPassword>>
>;
export type SignInEmailResult = NonNullable<Awaited<ReturnType<typeof signInEmail>>>;
export type ResetPasswordResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>;
export type GetAuthVerifyEmailResult = NonNullable<Awaited<ReturnType<typeof getAuthVerifyEmail>>>;
export type SendVerificationEmailResult = NonNullable<
  Awaited<ReturnType<typeof sendVerificationEmail>>
>;
export type ChangeEmailResult = NonNullable<Awaited<ReturnType<typeof changeEmail>>>;
export type ChangePasswordResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>;
export type UpdateUserResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>;
export type DeleteUserResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;
export type RequestPasswordResetResult = NonNullable<
  Awaited<ReturnType<typeof requestPasswordReset>>
>;
export type ResetPasswordCallbackResult = NonNullable<
  Awaited<ReturnType<typeof resetPasswordCallback>>
>;
export type ListUserSessionsResult = NonNullable<Awaited<ReturnType<typeof listUserSessions>>>;
export type PostAuthRevokeSessionResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRevokeSession>>
>;
export type PostAuthRevokeSessionsResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRevokeSessions>>
>;
export type PostAuthRevokeOtherSessionsResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRevokeOtherSessions>>
>;
export type LinkSocialAccountResult = NonNullable<Awaited<ReturnType<typeof linkSocialAccount>>>;
export type ListUserAccountsResult = NonNullable<Awaited<ReturnType<typeof listUserAccounts>>>;
export type GetAuthDeleteUserCallbackResult = NonNullable<
  Awaited<ReturnType<typeof getAuthDeleteUserCallback>>
>;
export type PostAuthUnlinkAccountResult = NonNullable<
  Awaited<ReturnType<typeof postAuthUnlinkAccount>>
>;
export type PostAuthRefreshTokenResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRefreshToken>>
>;
export type PostAuthGetAccessTokenResult = NonNullable<
  Awaited<ReturnType<typeof postAuthGetAccessToken>>
>;
export type GetAuthAccountInfoResult = NonNullable<Awaited<ReturnType<typeof getAuthAccountInfo>>>;
export type GetAuthOkResult = NonNullable<Awaited<ReturnType<typeof getAuthOk>>>;
export type GetAuthErrorResult = NonNullable<Awaited<ReturnType<typeof getAuthError>>>;
