/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

import { apiClient } from './http-client';
import type { CreateUserDto, HealthControllerCheck200 } from './model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getNestJSFoundationAPI = () => {
  /**
   * @summary Get hello message
   */
  const appControllerGetHello = (options?: SecondParameter<typeof apiClient<void>>) => {
    return apiClient<void>({ url: `/`, method: 'GET' }, options);
  };

  /**
   * @summary Create a new user (Zod validation example)
   */
  const appControllerCreateUser = (
    createUserDto: CreateUserDto,
    options?: SecondParameter<typeof apiClient<void>>
  ) => {
    return apiClient<void>(
      {
        url: `/users`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createUserDto,
      },
      options
    );
  };

  const prometheusControllerIndex = (options?: SecondParameter<typeof apiClient<void>>) => {
    return apiClient<void>({ url: `/metrics`, method: 'GET' }, options);
  };

  /**
   * @summary Health check endpoint
   */
  const healthControllerCheck = (
    options?: SecondParameter<typeof apiClient<HealthControllerCheck200>>
  ) => {
    return apiClient<HealthControllerCheck200>({ url: `/health`, method: 'GET' }, options);
  };

  return {
    appControllerGetHello,
    appControllerCreateUser,
    prometheusControllerIndex,
    healthControllerCheck,
  };
};
export type AppControllerGetHelloResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getNestJSFoundationAPI>['appControllerGetHello']>>
>;
export type AppControllerCreateUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getNestJSFoundationAPI>['appControllerCreateUser']>>
>;
export type PrometheusControllerIndexResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getNestJSFoundationAPI>['prometheusControllerIndex']>>
>;
export type HealthControllerCheckResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getNestJSFoundationAPI>['healthControllerCheck']>>
>;
